services:

  web:
    container_name: ikatoo-frontend
    image: nginx:alpine
    working_dir: /usr/share/nginx/html
    environment:
      VITE_API_SECRETS: ${VITE_API_SECRETS}
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    ports:
      - ${PORT}:80

