services:

  keycloak-db:
    container_name: keycloak-db
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_HOST: ${DB_HOST_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  keycloak-adminer:
    container_name: keycloak-adminer
    image: adminer
    links:
      - keycloak-db:${DB_HOST_NAME}
    depends_on:
      - keycloak-db
    ports:
      - ${ADMINER_PORT}:8080

  mail:
    image: dockage/mailcatcher:0.8.2
    ports:
      - ${MAIL_ADMIN_PORT}:1080

  keycloak:
    container_name: keycloak
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
      args:
        DB_HOST_NAME: ${DB_HOST_NAME}
        POSTGRES_DB: ${POSTGRES_DB_NAME}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./themes:/opt/keycloak/themes
    links:
      - keycloak-db:${DB_HOST_NAME}
      - mail
    depends_on:
      - keycloak-db
    ports:
      - ${KEYCLOAK_PORT}:8080
    command: start-dev
