version: '3.8'
services:
  keycloak:
    build:
      context: ./
      dockerfile: ./keycloak/Dockerfile.dev
      args:
        DB_HOST_NAME: ${DB_HOST_NAME}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    links:
      - postgres:${DB_HOST_NAME}
    depends_on:
      - postgres
    ports:
      - ${KEYCLOAK_PORT}:8080
    command: start-dev
